# Generated by Django 6.0 on 2025-12-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('system_prompt', models.TextField()),
                ('tools_config', models.JSONField(blank=True, null=True)),
                ('output_schema', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent',
                'indexes': [models.Index(fields=['name'], name='agent_name_8633c5_idx'), models.Index(fields=['is_active'], name='agent_is_acti_be3f7d_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_mapping', models.JSONField(blank=True, null=True)),
                ('output_mapping', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.agent')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('graph_definition', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_for_process', to='core.task')),
            ],
            options={
                'db_table': 'process',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name'], name='task_name_45563c_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['name'], name='process_name_d5fd7e_idx'),
        ),
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['is_active'], name='process_is_acti_550ba7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('name', 'version')},
        ),
    ]
