# Generated by Django 6.0 on 2025-12-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='llm_config',
            field=models.JSONField(default=dict, help_text='Configuração do LLM (provider, model, params)'),
        ),
    ]
