# Generated by Django 6.0 on 2025-12-21 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agent_llm_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField(help_text='Ex: results.output.confidence >= 0.8')),
                ('order', models.PositiveIntegerField(default=0)),
                ('from_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='core.task')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='core.process')),
                ('to_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='core.task')),
            ],
            options={
                'db_table': 'process_transitions',
                'ordering': ['order'],
            },
        ),
    ]
