# Generated by Django 6.0 on 2025-12-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_processtransition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='graph_definition',
        ),
    ]
