# Generated by Django 6.0 on 2026-01-11 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_processexecution_taskexecution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('restricted', 'Restricted'), ('public', 'Public'), ('open', 'Open')], default='restricted', help_text='Tipo de acesso ao processo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text="Grupos com acesso (apenas para access_type='restricted')", related_name='process_permissions', to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text="Usuários com acesso (apenas para access_type='restricted')", related_name='process_permissions', to=settings.AUTH_USER_MODEL)),
                ('process', models.OneToOneField(help_text='Processo ao qual esta permissão se aplica', on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='core.process')),
            ],
            options={
                'verbose_name': 'Process Permission',
                'verbose_name_plural': 'Process Permissions',
                'db_table': 'process_permission',
            },
        ),
    ]
