# Generated by Django 6.0 on 2026-02-13 12:11

from django.db import migrations, models

def migrate_schemas(apps, schema_editor):
    Agent = apps.get_model('core', 'Agent')
    Task = apps.get_model('core', 'Task')
    
    for task in Task.objects.select_related('agent'):
        if task.agent.output_schema:
            # Copia o schema do Agent para a Task
            task.output_schema = task.agent.output_schema
            task.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_processpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='output_schema',
            field=models.JSONField(blank=True, help_text='Define o formato de saída. Se None, retorna texto puro.', null=True),
        ),
        migrations.RunPython(migrate_schemas),
        migrations.RemoveField(
            model_name='agent',
            name='output_schema',
        )
    ]
