# Generated by Django 6.0 on 2026-02-23 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0007_remove_agent_output_schema_task_output_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('restricted', 'Restricted'), ('public', 'Public'), ('open', 'Open')], default='restricted', help_text='Tipo de acesso à task', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Permission',
                'verbose_name_plural': 'Task Permissions',
                'db_table': 'task_permission',
            },
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='process',
            name='process_name_d5fd7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='process',
            name='process_is_acti_550ba7_idx',
        ),
        migrations.RemoveField(
            model_name='processpermission',
            name='process',
        ),
        migrations.RemoveField(
            model_name='processtransition',
            name='process',
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='process_execution',
        ),
        migrations.RemoveField(
            model_name='processpermission',
            name='allowed_groups',
        ),
        migrations.RemoveField(
            model_name='processpermission',
            name='allowed_users',
        ),
        migrations.RemoveField(
            model_name='processtransition',
            name='from_task',
        ),
        migrations.RemoveField(
            model_name='processtransition',
            name='to_task',
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.task'),
        ),
        migrations.AddField(
            model_name='taskpermission',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text="Grupos com acesso (apenas para access_type='restricted')", related_name='task_permissions', to='auth.group'),
        ),
        migrations.AddField(
            model_name='taskpermission',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text="Usuários com acesso (apenas para access_type='restricted')", related_name='task_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskpermission',
            name='task',
            field=models.OneToOneField(help_text='Task à qual esta permissão se aplica', on_delete=django.db.models.deletion.CASCADE, related_name='permission', to='core.task'),
        ),
        migrations.RemoveField(
            model_name='process',
            name='entry_task',
        ),
        migrations.DeleteModel(
            name='ProcessExecution',
        ),
        migrations.DeleteModel(
            name='ProcessPermission',
        ),
        migrations.DeleteModel(
            name='ProcessTransition',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
